@echo off
setlocal enabledelayedexpansion
chcp 65001 > nul

set ROOT=C:\my\src\tree-sitter
set CORE_INC=%ROOT%\tree-sitter\lib\include
set CORE_SRC=%ROOT%\tree-sitter\lib\src\lib.c

set "LICENSE_OUT=THIRD_PARTY_LICENSES.txt"

(
echo ==================================================
echo Third Party Licenses
echo Generated by build.bat
echo ==================================================
echo.
)> "%LICENSE_OUT%"


echo [Building Core...]
cl /utf-8 /LD /MD /O2 /I "%CORE_INC%" "%CORE_SRC%" /Fe:"tree-sitter.dll" /link /DEF:"tree-sitter\win.def"

(
echo ==================================================
echo tree-sitter
echo ==================================================
echo.
type "tree-sitter\LICENSE"
echo.
)>> "%LICENSE_OUT%"

if exist "tree-sitter\lib\src\unicode\LICENSE" (
    (
    echo ==================================================
    echo tree-sitter - Unicode
    echo ==================================================
    echo.
    type "tree-sitter\lib\src\unicode\LICENSE"
    echo.
    )>> "%LICENSE_OUT%"
)



echo ERRORLEVEL=%ERRORLEVEL%
echo TMP=%TMP%
echo TEMP=%TEMP%

for /d %%G in (tree-sitter-*) do (
    set "dirName=%%G"

    if /i "%%G" neq "tree-sitter" (
        set "lang=!dirName:tree-sitter-=!"

        echo [Building !lang!...]

        if exist "%%G\src\parser.c" (
            set "SRC_FILES=%%G\src\parser.c"
            if exist "%%G\src\scanner.c" set "SRC_FILES=!SRC_FILES! %%G\src\scanner.c"
            if exist "%%G\src\scanner.cc" set "SRC_FILES=!SRC_FILES! %%G\src\scanner.cc"

            cl /LD /MD /O2 /I "%CORE_INC%" /I "%%G\src" !SRC_FILES! /Fe:tree-sitter-!lang!.dll
            copy /Y "%%G\queries\highlights.scm" "!lang!_highlights.scm" >nul 2>&1
            copy /Y "%%G\queries\injections.scm" "!lang!_injections.scm" >nul 2>&1
            copy /Y "%%G\queries\tags.scm" "!lang!_tags.scm" >nul 2>&1
        )
        if exist "%%G\php\src\parser.c" (
            set "SRC_FILES=%%G\php\src\parser.c"
            if exist "%%G\php\src\scanner.c" set "SRC_FILES=!SRC_FILES! %%G\php\src\scanner.c"
            if exist "%%G\php\src\scanner.cc" set "SRC_FILES=!SRC_FILES! %%G\php\src\scanner.cc"

            cl /LD /MD /O2 /I "%CORE_INC%" /I "%%G\php\src" !SRC_FILES! /Fe:tree-sitter-!lang!.dll
            copy /Y "%%G\queries\highlights.scm" "!lang!_highlights.scm" >nul 2>&1
            copy /Y "%%G\queries\injections.scm" "!lang!_injections.scm" >nul 2>&1
            copy /Y "%%G\queries\tags.scm" "!lang!_tags.scm" >nul 2>&1
        )
        if exist "%%G\typescript\src\parser.c" (
            set "SRC_FILES=%%G\typescript\src\parser.c"
            if exist "%%G\typescript\src\scanner.c" set "SRC_FILES=!SRC_FILES! %%G\typescript\src\scanner.c"
            if exist "%%G\typescript\src\scanner.cc" set "SRC_FILES=!SRC_FILES! %%G\typescript\src\scanner.cc"

            cl /LD /MD /O2 /I "%CORE_INC%" /I "%%G\typescript\src" !SRC_FILES! /Fe:tree-sitter-!lang!.dll
            copy /Y "%%G\queries\highlights.scm" "!lang!_highlights.scm" >nul 2>&1
            copy /Y "%%G\queries\injections.scm" "!lang!_injections.scm" >nul 2>&1
            copy /Y "%%G\queries\tags.scm" "!lang!_tags.scm" >nul 2>&1
        )
        if exist "%%G\tsx\src\parser.c" (
            set "SRC_FILES=%%G\tsx\src\parser.c"
            if exist "%%G\tsx\src\scanner.c" set "SRC_FILES=!SRC_FILES! %%G\tsx\src\scanner.c"
            if exist "%%G\tsx\src\scanner.cc" set "SRC_FILES=!SRC_FILES! %%G\tsx\src\scanner.cc"

            cl /LD /MD /O2 /I "%CORE_INC%" /I "%%G\tsx\src" !SRC_FILES! /Fe:tree-sitter-tsx.dll
            copy /Y "%%G\queries\highlights.scm" "tsx_highlights.scm" >nul 2>&1
            copy /Y "%%G\queries\injections.scm" "tsx_injections.scm" >nul 2>&1
            copy /Y "%%G\queries\tags.scm" "tsx_tags.scm" >nul 2>&1
        )

        if exist "%%G\LICENSE" (
            (
            echo ==================================================
            echo tree-sitter-!lang!
            echo ==================================================
            echo.
            type "%%G\LICENSE"
            echo.
            )>> "%LICENSE_OUT%"
        ) else (
            echo ERROR: LICENSE not found: %%G\LICENSE
            exit /b 1
        )
    )
)

echo.
echo === Build Finished ===
echo [Final Check]
dumpbin /exports tree-sitter.dll | findstr "ts_parser_new"

pause